#+title: REK Søknad (#508643)

Prosjekt tittle: *Skader i Norge: analyse av data i Fyrtårnprosjektet* (#508643)

Informasjon som skal legges i søknaden

* 2:  Prosjektopplysninger og metode
** 2.1 Prosjektbeskrivelse
I de siste tiårene har statistikk for veitrafikken i Norge vist nedgang i antall ulykker og færre er drepte. Imidlertid har det blitt påpekt at den offisielle trafikkulykkestatistikken har en betydelig underrapportering av skader særlig for ulykker med lettere skader, men også for mer alvorlige skader. En nyere kartlegging anslått at dataene bare dekket 40% av hardt skadde pasienter. Årsaken er at offisielle trafikkulykkestatistikken er basert på politiregisterte ulykker. Ikke alle trafikkulykkeskadde pasienter som behandles i helsetjenesten er inkludert i politiregisteret. Lav dekningsgrad i politiregisteret gjør det utfordrende å tallfeste det reelle omfanget av skader i trafikken og følge utviklingen av trafikkulykker over tid. Med ufullstendig oversikt over det reelle antallet skadde blir det vanskelig å målrette trafikksikkerhetstiltak og evaluere om tiltak virker. Derfor har samferdselsmyndighetene i 2021 finansiert et kartleggingsarbeid om hvordan skaderegistrering i helsetjenesten kan bidra til forbedring i den offisielle trafikkulykkestatistikken.

Dette arbeidet fører til oppstart av Fyrtårnprosjektet om å etablere et system for å samle inn gode skadedata ved et utvalg "fyrtårn" bestående av ti sykehus og syv kommunale legevakter. Samlet sett skal data fra dette utvalget gi et representativt bilde av skadeomfanget i hele landet, i første omgang for trafikkulykker. Senere kan alle type skader og ulykker også bli kartlagt. Prosjektet skal styrke innsamlingen av data inkludert produksjon av statistikk og analyser på skadefeltet. Hoved data fra "fyrtårn" enhetene kommer fra opplysninger som sendes til Norsk pasientregister (NPR), inkludert en utvidet registreringsmodul for personskader dvs. Felles minimum datasett (FMDS). I tillegg skal data fra Nasjonalt traumeregister (NTR) og Kommunalt pasient- og brukerregister (KPR) brukes til å sikre data kvalitet og dekning for både lettere og alvorlige skader. Det er også opprettes en 20% skadekoordinatorstilling ved "fyrtårn" enhetene for å styrke registreringen. Den innsamlende data fra disse data kildene skal bidra til økt datakvalitet og gi valide statistikk over skadde pasienter behandles i helsetjenesten som følge av trafikkulykker.

* 3: Forskningsdata
** 3.2.2.1 Opplysninger fra Sentrale helseregistre
  Hvilke opplysninger skal hentes. Oppgi kategorier av variabler og anslag på antall
  + Norsk pasientregister
    Opplysninger om alle pasienter behandlet for skader, identifisert via diagnosekoder fra kapittel XIX og XX i ICD-10 i aktivitetsdata somatikk og data registeret i FMDS. Variabler: demografiske variabler, diagnosekoder, behandlingssted, dato for inn- og utskrivning, kontaktårsak skade, ytre omstendigheter, alvorlighetsgrad, geografisk stedfesting (ca. 25 variabler)
  + Kommunalt pasient- og brukerregister (KPR)
    Opplysninger om pasienter som oppsøkte primærhelsetjenesten for skader. Variabler: demografiske variabler, diagnosekoder iht. ICPC-2 og kontakt relatert informasjon (ca. 9 variabler)
  + Nasjonalt traumeregister (NTR)
    Opplysninger om alvorlige skadde pasienter behandlet i spesialisthelsetjenesten. Variabler: demografiske variabler, ulykke hendelse informasjon, innleggelse relatert informasjon og koder om tilstand for pasienter (ca. 20 variabler)
  + Annen register
    - Politiets database over trafikkulykker med personskade gir opplysninger om alle trafikkulykker med personskade som rapporteres til politiet. Variabler: demografiske variabler, ulykke hendelse informasjon, skade alvorlighetsgrad, beskyttelsesutstyr og ferdselsform (ca. 10 variabler)
** TODO 3.2.11.1 Beskriv hvordan data skal kobles sammen
Data skal kobles via person avidentifisert løpenummer. /[men hvem skal lage løpenummeret? Hvordan skal det håndteres for løpende rapportering når det kan ta tid før SSB kan levere koblingsnøkkel for personnummer]/

** 3.6 Begrunnelsen for data og metode
Den offisielle trafikkulykkestatistikken i Norge er basert på data fra politiet database over trafikkulykker. Det har vært påpekt at databasen dekker bare 40% av hardt skadde. For å kunne øke dekningsgraden for rapportering av lettere og alvorlige ulykkeskader er det behov for å hente data fra andre kilder. Norsk pasientregister (NPR) har informasjon relatert til alle type skader inkludert en tilpasset felles minimum datasett (FMDS) for skade. Alle skadde pasienter som oppsøkte spesialisthelsetjenesten blir registret i NPR. Skade data fra Kommunalt pasient- og brukerregister (KPR) dekker pasienter som har oppsøkt primærhelsetjenesten. Koblingen av begge dataene bidrar til en betydelig økning i dekningsgraden av skade rapportering. Data fra Nasjonalt traumeregister (NTR) er viktig for å sikre kvaliteten i skade alvorlighetsgradering og for at mest mulig alvorlige skadde pasienter er inkludert i statistikken. Høy dekningsgrad av ulykkeskade rapportering bidra til valide bilder av ulykkesstatistikken evt. evaluering av sikkerhettiltak i trafikken.

* 4: Avveining av nytte og risiko

** 4.1 Angi forutsigbar nytte eller fordeler

*** 6.1 For den enkelte deltaker/pasient
Inkluderte pasienter i registrene vil ikke ha direkte nytte ved prosjektet

*** 6.2 For gruppen
Statistikken vil gi et mer korrekt bilder av trafikkulykker i Norge. Dette bidra til at trafikkmyndighetene kan sette riktige og relevante tiltak i trafikken som har nytteverdi for alle trafikanter. Vurdering av de tiltakene vil også blir mer presise.

*** 6.3 Nå eller i fremtiden for samfunnet eller vitenskapen
Samfunnet:
- Mer tryggere i trafikken
- Tiltak for å redusere antall trafikkulykker

Vitenskapen:
- Bedre forståelse av trafikkulykker i Norge overtid
- Målrettet arbeid å forebygge personskader i trafikken
** 4.2 Angi mulig risiko/ulempe nå eller i fremtiden
*** 6.4 For den enkelte deltaker/pasient
Det er ingen risiko eller ulempe for den inkluderte pasientene siden resultatene vil bli presentert på aggregert nivå. Anonymitet skal opprettholdes ved at ingen resultat bli vist når antall individer er mindre enn 6 personer.
*** 6.5 For gruppen
Det er ingen risiko eller ulempe for den inkluderte gruppen siden resultatene vil bli presentert på aggregert nivå. Anonymitet skal opprettholdes ved at ingen resultat bli vist når antall individer er mindre enn 6 personer.
*** 6.6 For samfunnet eller vitenskapen
Ingen
** 4.4 Tiltak
*** TODO 6.7 Redegjør for tiltak
- Konfidensialitet (skal SSB produserer løpenummer?)
- Skal TSD brukes?

Utleverte data vil behandles konfidensielt i henhold til eksisterende lovverk for forskningsdata og basert på databehandleravtale mellom FHI og de utleverende registrene. Dette innebærer at data er oppbevart og beskyttet gjennom strenge sikkerhetsrutiner. Data som utleveres til forskere er avidentifisert, ved at personnummer er slettet og erstattet av prosjektspesifikt løpenummer.

Prosjektet vil ellers følge etiske retningslinjer for forskning ved metode, statistiske analyser og presentasjon av resultater. Ved presentasjon av resultater vil det tas hensyn til både personvern og statistisk robusthet. Alle analyseresultater vil presenteres på gruppenivå, og resultater basert på svært få tilfeller (< 6 individer) vil verken presenteres eller diskuteres.


** 4.5 Forsvarlighet
*** TODO 6.8 Gi en samlet vurdering av prosjektets forsvarlighet for å begrunne at nytten står i et rimelig forhold til den risiko/ulempe som pasienter/deltakere utsettes for
I dette prosjektet vil vi benytte allerede innsamlede registeropplysninger til å øke kunnskapsnivået om trafikkulykker i Norge. Det er lagt ned mye ressurser i innsamling av helseopplysninger og vi anser det etisk forsvarlig å benytte dataene for å skaffe til veie økt kunnskap som i nær fremtid vil kunne brukes til å inføre tiltak for forebygging av trafikkulykker. De inkluderte personene vil ikke utsettes for risiko eller ubehag. Potensiell risiko for personvernet ved å delta i studien minskes av at pasienter har anledning til å reservere seg mot deltakelse i NTR og at det legges opp til høy grad av beskyttelse mot personvernulemper, herunder datahåndtering med høy grad av datasikkerhet i henhold til gjeldende retningslinjer (GDPR), utarbeidelse av personvernkonsekvensutredning, avgrensning av datakilder, variabler og aldersgrupper som inngår i de ulike problemstillingene, gruppering av spesielt sensitive opplysninger i det endelige datasettet, samt et stort antall inkluderte pasienter. Undergrupper av pasienter inndelt etter alder, geografiske regioner og lignende vil være tallmessige så store at personvernkonsekvensene reduseres betraktelig.
* 5 Studiepopulasjon og samtykke
** Samtykke
*** 5.6.2.1.1 Begrunn hvorfor det ikke kan innhentes samtykke
Prosjektet skal produsere løpende skadestatistikk basert på en allerede innsamlede opplysninger om trafikkulykker. Det vil være uhensiktsmessig å innhente samtykke hver gang statistikken skal produseres.
